# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
# Build at 00:00 on every 12th day-of-month.
  - cron: '0 0 */12 * *'
# Allows you to run this workflow manually from the Actions tab   
  workflow_dispatch:
    branches:
    - master
# Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore: [ '**/README.md' ]
  pull_request:
    branches: [ "main" ]
    paths-ignore: [ '**/README.md' ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
  build:
# The type of runner that the job will run on
    runs-on: void-latest

# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

# Runs a single command using the runners shell
      - name: Build xbps
        run: |                
        
      - name: release
        uses: "sofijacom/action-automatic-releases@6273874b61ebc8c71f1a61b2d98e234cf389b303"
        with:
          title: Continuous build
          automatic_release_tag: continuous-stable
          prerelease: false
          draft: false
          files: /home/runner/work/yandex-browser/yandex-browser/*.xbps*
          repo_token: "${{ secrets.GITHUB_TOKEN }}"

# Runs a set of commands using the runners shell
      - name: Delete old releases
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
